openapi: 3.0.1
info:
  contact:
    name: Sonatype Community Maintainers
    url: https://github.com/sonatype-nexus-community
  description: This documents the available APIs into [Sonatype Nexus Repository Manager](https://www.sonatype.com/products/sonatype-nexus-repository) as of version 3.91.0-07.
  license:
    name: Apache-2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Sonatype Nexus Repository Manager assets Reconcile Plan API
  version: 3.91.0-07
servers:
- url: /service/rest/
security:
- BasicAuth: []
tags:
- name: Reconcile Plan
paths:
  /v1/plan:
    delete:
      operationId: deleteAllPlans
      responses:
        '204':
          content: {}
          description: Reconciliation plans deleted
        '401':
          content: {}
          description: Authentication required
        '403':
          content: {}
          description: Insufficient permissions
        '404':
          content: {}
          description: Plan not found
      summary: Delete all non executed reconciliation plans
      tags:
      - Reconcile Plan
    get:
      operationId: getAvailablePlans
      parameters:
      - description: A token returned by a prior request. If present, the next page of results are returned
        in: query
        name: continuationToken
        schema:
          type: string
      responses:
        '200':
          content: {}
          description: List of plans found
        '401':
          content: {}
          description: Authentication required
        '403':
          content: {}
          description: Insufficient permissions
      summary: Get list of currently available plans
      tags:
      - Reconcile Plan
    post:
      operationId: createReconciliationPlans
      parameters:
      - allowEmptyValue: true
        description: repository(ies) which should be processed with high priority
        explode: true
        in: query
        name: repositories
        schema:
          items:
            type: string
          type: array
        style: form
      - allowEmptyValue: true
        explode: true
        in: query
        name: blobStores
        schema:
          items:
            type: string
          type: array
        style: form
      - in: query
        name: startDate
        schema:
          type: string
      - in: query
        name: endDate
        schema:
          type: string
      - in: query
        name: sinceDays
        schema:
          format: int32
          type: integer
      - in: query
        name: sinceHours
        schema:
          format: int32
          type: integer
      - in: query
        name: sinceMinutes
        schema:
          default: 30
          format: int32
          type: integer
      responses:
        '204':
          content: {}
          description: Reconciliation plans created and executed
        '401':
          content: {}
          description: Authentication required
        '403':
          content: {}
          description: Insufficient permissions
        '404':
          content: {}
          description: Reconciliation plan not found
      summary: Create reconciliation plans with selected parameters
      tags:
      - Reconcile Plan
    put:
      operationId: executeReconcileTasks
      responses:
        '204':
          content: {}
          description: Reconciliation plans executed
        '401':
          content: {}
          description: Authentication required
        '403':
          content: {}
          description: Insufficient permissions
        '404':
          content: {}
          description: Reconciliation plan not found
      summary: Execute all non executed reconciliation plans
      tags:
      - Reconcile Plan
  /v1/plan/details:
    get:
      operationId: getPlanDetails
      parameters:
      - description: Id of the plan
        in: query
        name: planId
        schema:
          format: int32
          type: integer
      - in: query
        name: state
        schema:
          type: string
      - in: query
        name: repository
        schema:
          type: string
      - description: A token returned by a prior request. If present, the next page of results are returned
        in: query
        name: continuationToken
        schema:
          type: string
      responses:
        '200':
          content: {}
          description: Reconciliation plan details found
        '401':
          content: {}
          description: Authentication required
        '403':
          content: {}
          description: Insufficient permissions
      summary: Get reconciliation plan details
      tags:
      - Reconcile Plan
  /v1/plan/{planId}:
    delete:
      operationId: deletePlan
      parameters:
      - description: Id of the plan to delete
        in: path
        name: planId
        required: true
        schema:
          format: int32
          type: integer
      responses:
        '204':
          content: {}
          description: Reconciliation plan deleted
        '401':
          content: {}
          description: Authentication required
        '403':
          content: {}
          description: Insufficient permissions
        '404':
          content: {}
          description: Plan not found
      summary: Delete a reconciliation plan based on its Id
      tags:
      - Reconcile Plan
    get:
      operationId: getSinglePlanWithDetails
      parameters:
      - description: Id of the plan
        in: path
        name: planId
        required: true
        schema:
          format: int32
          type: integer
      - in: query
        name: repository
        schema:
          type: string
      - description: A token returned by a prior request. If present, the next page of results are returned
        in: query
        name: continuationToken
        schema:
          type: string
      responses:
        '200':
          content: {}
          description: Reconciliation plan found
        '401':
          content: {}
          description: Authentication required
        '403':
          content: {}
          description: Insufficient permissions
      summary: Get single reconciliation plan with details
      tags:
      - Reconcile Plan
    put:
      operationId: executeReconcileTaskById
      parameters:
      - description: Id of the plan to execute
        in: path
        name: planId
        required: true
        schema:
          format: int32
          type: integer
      responses:
        '204':
          content: {}
          description: Reconciliation plans executed
        '401':
          content: {}
          description: Authentication required
        '403':
          content: {}
          description: Insufficient permissions
        '404':
          content: {}
          description: Reconciliation plan not found
      summary: Execute a reconciliation plan based on its Id
      tags:
      - Reconcile Plan
components:
  securitySchemes:
    BasicAuth:
      scheme: basic
      type: http
x-original-swagger-version: '2.0'
